apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: seroter-cloud-run-pipeline
description: application deployment pipeline
serialPipeline:
 stages:
 - targetId: core-dev
   profiles: [dev]
 - targetId: core-qa
   profiles: [qa]
 - targetId: core-prod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: core-dev
description: Cloud Run development service
run:
 location: projects/seroter-project-base/locations/us-west1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: core-qa
description: Cloud Run qa service
run:
 location: projects/seroter-project-base/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: core-prod
description: Cloud Run prod service
run:
 location: projects/seroter-project-base/locations/us-south1
